name: Manual
on:
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                description: A cheerhul word
                required: true
                default: Hello
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.greeting }}"
